name: country_data
description: A Package That Provide Country Data Like Name, PhoneCode, Currency, States and Cities etc.
version: 0.0.1
homepage: https://github.com/CodeWithNav/country_data

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
